# Handle Errors
## HTTPException
Wenn man dem User einen Error geben möchte macht man das mit der `HTTPException`


```py
from fastapi import FastAPI, HTTPException

app = FastAPI()

items = {"foo": "bar"}

@app.post("/items/{item_name}")
async def get_item(item_name: str):
    if item_name not in items:
        raise HTTPException(status_code=404, detail="Item not found")
    return items[item_name]
```
Die `HTTPException` nimmt einen Status Code und Optional noch Details aber auch `headers` können gesetzt werden.

## Custom Errors
Man kann eigene `Exceptions` machen die von einem `Exeception Handler` verarbeitet werden.

```py
from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse

app = FastAPI()

class MyExeception(Exception):
    name: str

    def __init__(self, name: str):
        self.name = name

items = {"foo": "bar"}

@app.post("/items/{item_name}")
async def get_item(item_name: str):
    if item_name not in items:
        raise MyExeception(item_name)
    return items[item_name]

@app.exception_handler(MyExeception)
async def handle_myexeception(_: Request, e: MyExeception):
    return JSONResponse(f"Item not found: {e.name}", status_code=404)
```
Der `Exeception Handler` als Parameter den `Request` und die `Exception`